// Generated by tools/embed_shaders.py -- do not edit.
#pragma once

namespace kzgpu {
inline const char *kShaderSource = R"KZGPU_SHADER_SRC(
#include <metal_stdlib>
using namespace metal;

#line 1 "src/layout_defs.h"
/*
 * Single source of truth for the sizes shared between host and device.
 *
 * This file is plain #defines so that it can be included by C++ *and*
 * concatenated into the Metal shader source.  kzgpu_internal.h turns these
 * into typed constexprs for the host; the shaders use the macros directly.
 */
#ifndef KZGPU_LAYOUT_DEFS_H
#define KZGPU_LAYOUT_DEFS_H

#define L_FIELD_ELEMENTS_PER_BLOB 4096
#define L_FIELD_ELEMENTS_PER_EXT_BLOB 8192
#define L_FIELD_ELEMENTS_PER_CELL 64
#define L_CELLS_PER_BLOB 64
#define L_CELLS_PER_EXT_BLOB 128
#define L_CIRCULANT_SIZE 128
#define L_BYTES_PER_FIELD_ELEMENT 32
#define L_BYTES_PER_BLOB 131072
#define L_BYTES_PER_PROOF 48

#define L_LOG_BLOB 12
#define L_LOG_EXT_BLOB 13
#define L_LOG_CIRCULANT 7

/* Signed-digit MSM window. */
#define L_WINDOW_BITS 8
#define L_NUM_DIGITS 32
#define L_NUM_BUCKETS 128

#define L_PHASE_A_TERMS 64
#define L_PHASE_A_ITEMS 2048 /* L_PHASE_A_TERMS * L_NUM_DIGITS */
#define L_PHASE_B_TERMS 65
#define L_PHASE_B_ITEMS 2080 /* L_PHASE_B_TERMS * L_NUM_DIGITS */
#define L_LADDER_POSITIONS 32

/* Element sizes in uint32 words. */
#define L_FP_WORDS 12
#define L_FR_WORDS 8
#define L_AFFINE_WORDS 24
#define L_JACOBIAN_WORDS 36

/*
 * Bucket reduction: L_REDUCE_LANES lanes cooperate on one output, each first
 * collapsing L_NUM_BUCKETS / L_REDUCE_LANES buckets serially.  8 lanes keeps
 * the shuffle-tree width small while leaving the serial chain short enough.
 */
#define L_REDUCE_LANES 8
#define L_REDUCE_PER_LANE 16 /* L_NUM_BUCKETS / L_REDUCE_LANES */
#define L_LOG_REDUCE_PER_LANE 4
#define L_REDUCE_OUTPUTS_PER_TG 16 /* 128 threads / L_REDUCE_LANES */

#endif /* KZGPU_LAYOUT_DEFS_H */

#line 1 "src/shaders/bls12_381_constants.h.inc"
/* Generated by tools/gen_constants.py -- do not edit. */
/* Device-side (Metal) constants: 32-bit limbs, little endian. */
#define FP_NLIMBS 12
#define FR_NLIMBS 8

constant uint FP_P[12] = { 0xffffaaabu, 0xb9feffffu, 0xb153ffffu, 0x1eabfffeu, 0xf6b0f624u, 0x6730d2a0u, 0xf38512bfu, 0x64774b84u, 0x434bacd7u, 0x4b1ba7b6u, 0x397fe69au, 0x1a0111eau };
constant uint FP_N0 = 0xfffcfffdu;
constant uint FP_R[12] = { 0x0002fffdu, 0x76090000u, 0xc40c0002u, 0xebf4000bu, 0x53c758bau, 0x5f489857u, 0x70525745u, 0x77ce5853u, 0xa256ec6du, 0x5c071a97u, 0xfa80e493u, 0x15f65ec3u };
constant uint FP_R2[12] = { 0x1c341746u, 0xf4df1f34u, 0x09d104f1u, 0x0a76e6a6u, 0x4c95b6d5u, 0x8de5476cu, 0x939d83c0u, 0x67eb88a9u, 0xb519952du, 0x9a793e85u, 0x92cae3aau, 0x11988fe5u };
constant uint FP_BETA[12] = { 0x8671f071u, 0xcd03c9e4u, 0x1fcda5d2u, 0x5dab2246u, 0xd3851b95u, 0x587042afu, 0x01bacb9eu, 0x8eb60ebeu, 0x83d050d2u, 0x03f97d6eu, 0x54638741u, 0x18f02065u };
constant uint FR_P[8] = { 0x00000001u, 0xffffffffu, 0xfffe5bfeu, 0x53bda402u, 0x09a1d805u, 0x3339d808u, 0x299d7d48u, 0x73eda753u };
constant uint FR_N0 = 0xffffffffu;
constant uint FR_ONE[8] = { 0xfffffffeu, 0x00000001u, 0x00034802u, 0x5884b7fau, 0xecbc4ff5u, 0x998c4fefu, 0xacc5056fu, 0x1824b159u };
constant uint FR_R2[8] = { 0xf3f29c6du, 0xc999e990u, 0x87925c23u, 0x2b6cedcbu, 0x7254398fu, 0x05d31496u, 0x9f59ff11u, 0x0748d9d9u };

#line 1 "src/shaders/field.metal"
// BLS12-381 arithmetic for Metal.
//
// Fp is 12 x 32-bit limbs, Fr is 8 x 32-bit limbs, both little-endian and in
// Montgomery form.  Multiplication is CIOS with a 64-bit accumulator: on Apple7
// that measured ~374M Fp multiplies/s, about 25% faster than hand-rolled 32-bit
// carry chains, because the compiler maps `(ulong)a*b` onto mul/mulhi directly.
//
// The constants block (FP_P, FP_N0, ...) is prepended from
// bls12_381_constants.h.inc, which is generated alongside the host constants.

// ---------------------------------------------------------------------- Fp

struct Fp {
    uint v[FP_NLIMBS];
};

struct Fr {
    uint v[FR_NLIMBS];
};

static inline Fp fp_zero() {
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.v[i] = 0u;
    return r;
}

static inline Fp fp_one() {
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.v[i] = FP_R[i];
    return r;
}

static inline bool fp_is_zero(thread const Fp &a) {
    uint acc = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) acc |= a.v[i];
    return acc == 0u;
}

static inline bool fp_eq(thread const Fp &a, thread const Fp &b) {
    uint acc = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) acc |= (a.v[i] ^ b.v[i]);
    return acc == 0u;
}

static inline Fp fp_add(thread const Fp &a, thread const Fp &b) {
    uint t[FP_NLIMBS];
    uint carry = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        ulong s = (ulong)a.v[i] + (ulong)b.v[i] + (ulong)carry;
        t[i] = (uint)s;
        carry = (uint)(s >> 32);
    }
    // p has room in the top limb, so the sum never overflows 12 limbs.
    uint s2[FP_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        ulong d = (ulong)t[i] - (ulong)FP_P[i] - (ulong)borrow;
        s2[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.v[i] = borrow ? t[i] : s2[i];
    return r;
}

static inline Fp fp_sub(thread const Fp &a, thread const Fp &b) {
    uint t[FP_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        ulong d = (ulong)a.v[i] - (ulong)b.v[i] - (ulong)borrow;
        t[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    uint carry = 0u;
    uint mask = borrow ? 0xffffffffu : 0u;
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        ulong s = (ulong)t[i] + (ulong)(FP_P[i] & mask) + (ulong)carry;
        r.v[i] = (uint)s;
        carry = (uint)(s >> 32);
    }
    return r;
}

static inline Fp fp_neg(thread const Fp &a) {
    if (fp_is_zero(a)) return a;
    Fp z = fp_zero();
    return fp_sub(z, a);
}

static inline Fp fp_dbl(thread const Fp &a) { return fp_add(a, a); }

static inline Fp fp_mul(thread const Fp &a, thread const Fp &b) {
    uint t[FP_NLIMBS + 2];
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS + 2; i++) t[i] = 0u;

#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        uint c = 0u;
        const uint bi = b.v[i];
#pragma clang loop unroll(full)
        for (int j = 0; j < FP_NLIMBS; j++) {
            ulong s = (ulong)a.v[j] * (ulong)bi + (ulong)t[j] + (ulong)c;
            t[j] = (uint)s;
            c = (uint)(s >> 32);
        }
        ulong s = (ulong)t[FP_NLIMBS] + (ulong)c;
        t[FP_NLIMBS] = (uint)s;
        t[FP_NLIMBS + 1] = (uint)(s >> 32);

        const uint m = t[0] * FP_N0;
        ulong s0 = (ulong)m * (ulong)FP_P[0] + (ulong)t[0];
        c = (uint)(s0 >> 32);
#pragma clang loop unroll(full)
        for (int j = 1; j < FP_NLIMBS; j++) {
            ulong sj = (ulong)m * (ulong)FP_P[j] + (ulong)t[j] + (ulong)c;
            t[j - 1] = (uint)sj;
            c = (uint)(sj >> 32);
        }
        ulong sn = (ulong)t[FP_NLIMBS] + (ulong)c;
        t[FP_NLIMBS - 1] = (uint)sn;
        t[FP_NLIMBS] = t[FP_NLIMBS + 1] + (uint)(sn >> 32);
    }

    // The CIOS result is below 2p; subtract once when needed.
    uint s2[FP_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) {
        ulong d = (ulong)t[i] - (ulong)FP_P[i] - (ulong)borrow;
        s2[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    borrow = (t[FP_NLIMBS] < borrow) ? 1u : 0u;
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.v[i] = borrow ? t[i] : s2[i];
    return r;
}

static inline Fp fp_sqr(thread const Fp &a) { return fp_mul(a, a); }

// ---------------------------------------------------------------------- Fr

static inline Fr fr_zero() {
    Fr r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) r.v[i] = 0u;
    return r;
}

static inline bool fr_is_zero(thread const Fr &a) {
    uint acc = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) acc |= a.v[i];
    return acc == 0u;
}

static inline Fr fr_add(thread const Fr &a, thread const Fr &b) {
    uint t[FR_NLIMBS];
    uint carry = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        ulong s = (ulong)a.v[i] + (ulong)b.v[i] + (ulong)carry;
        t[i] = (uint)s;
        carry = (uint)(s >> 32);
    }
    uint s2[FR_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        ulong d = (ulong)t[i] - (ulong)FR_P[i] - (ulong)borrow;
        s2[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    Fr r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) r.v[i] = borrow ? t[i] : s2[i];
    return r;
}

static inline Fr fr_sub(thread const Fr &a, thread const Fr &b) {
    uint t[FR_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        ulong d = (ulong)a.v[i] - (ulong)b.v[i] - (ulong)borrow;
        t[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    uint mask = borrow ? 0xffffffffu : 0u;
    uint carry = 0u;
    Fr r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        ulong s = (ulong)t[i] + (ulong)(FR_P[i] & mask) + (ulong)carry;
        r.v[i] = (uint)s;
        carry = (uint)(s >> 32);
    }
    return r;
}

static inline Fr fr_mul(thread const Fr &a, thread const Fr &b) {
    uint t[FR_NLIMBS + 2];
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS + 2; i++) t[i] = 0u;

#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        uint c = 0u;
        const uint bi = b.v[i];
#pragma clang loop unroll(full)
        for (int j = 0; j < FR_NLIMBS; j++) {
            ulong s = (ulong)a.v[j] * (ulong)bi + (ulong)t[j] + (ulong)c;
            t[j] = (uint)s;
            c = (uint)(s >> 32);
        }
        ulong s = (ulong)t[FR_NLIMBS] + (ulong)c;
        t[FR_NLIMBS] = (uint)s;
        t[FR_NLIMBS + 1] = (uint)(s >> 32);

        const uint m = t[0] * FR_N0;
        ulong s0 = (ulong)m * (ulong)FR_P[0] + (ulong)t[0];
        c = (uint)(s0 >> 32);
#pragma clang loop unroll(full)
        for (int j = 1; j < FR_NLIMBS; j++) {
            ulong sj = (ulong)m * (ulong)FR_P[j] + (ulong)t[j] + (ulong)c;
            t[j - 1] = (uint)sj;
            c = (uint)(sj >> 32);
        }
        ulong sn = (ulong)t[FR_NLIMBS] + (ulong)c;
        t[FR_NLIMBS - 1] = (uint)sn;
        t[FR_NLIMBS] = t[FR_NLIMBS + 1] + (uint)(sn >> 32);
    }

    uint s2[FR_NLIMBS];
    uint borrow = 0u;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) {
        ulong d = (ulong)t[i] - (ulong)FR_P[i] - (ulong)borrow;
        s2[i] = (uint)d;
        borrow = (uint)((d >> 32) & 1u);
    }
    borrow = (t[FR_NLIMBS] < borrow) ? 1u : 0u;
    Fr r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) r.v[i] = borrow ? t[i] : s2[i];
    return r;
}

// Leaves Montgomery form: multiplying by 1 divides out R.
static inline Fr fr_to_canonical(thread const Fr &a) {
    Fr one = fr_zero();
    one.v[0] = 1u;
    return fr_mul(a, one);
}

// Enters Montgomery form.
static inline Fr fr_from_canonical(thread const Fr &a) {
    Fr r2;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) r2.v[i] = FR_R2[i];
    return fr_mul(a, r2);
}

// true when a < r, i.e. the value is a canonical field element.
static inline bool fr_is_canonical(thread const Fr &a) {
    for (int i = FR_NLIMBS - 1; i >= 0; i--) {
        if (a.v[i] != FR_P[i]) return a.v[i] < FR_P[i];
    }
    return false; // exactly r
}

// ---------------------------------------------------------------------- G1

// Jacobian (X : Y : Z) == (X/Z^2, Y/Z^3); Z == 0 is the point at infinity.
struct G1 {
    Fp x, y, z;
};
// Affine, with (0, 0) reserved for the point at infinity.
struct G1A {
    Fp x, y;
};

static inline G1 g1_identity() {
    G1 r;
    r.x = fp_zero();
    r.y = fp_one();
    r.z = fp_zero();
    return r;
}

static inline bool g1_is_identity(thread const G1 &p) { return fp_is_zero(p.z); }

static inline bool g1a_is_identity(thread const G1A &p) {
    return fp_is_zero(p.x) && fp_is_zero(p.y);
}

// dbl-2009-l, for curves with a == 0.
static inline G1 g1_dbl(thread const G1 &p) {
    if (fp_is_zero(p.z)) return p;
    Fp A = fp_sqr(p.x);
    Fp B = fp_sqr(p.y);
    Fp C = fp_sqr(B);
    Fp t0 = fp_add(p.x, B);
    t0 = fp_sqr(t0);
    t0 = fp_sub(t0, A);
    t0 = fp_sub(t0, C);
    Fp D = fp_dbl(t0);
    Fp E = fp_add(fp_dbl(A), A);
    Fp F = fp_sqr(E);
    G1 r;
    r.x = fp_sub(F, fp_dbl(D));
    Fp t1 = fp_sub(D, r.x);
    t1 = fp_mul(E, t1);
    Fp t2 = fp_dbl(fp_dbl(fp_dbl(C)));
    r.y = fp_sub(t1, t2);
    r.z = fp_dbl(fp_mul(p.y, p.z));
    return r;
}

// add-2007-bl
static inline G1 g1_add(thread const G1 &a, thread const G1 &b) {
    if (fp_is_zero(a.z)) return b;
    if (fp_is_zero(b.z)) return a;
    Fp Z1Z1 = fp_sqr(a.z);
    Fp Z2Z2 = fp_sqr(b.z);
    Fp U1 = fp_mul(a.x, Z2Z2);
    Fp U2 = fp_mul(b.x, Z1Z1);
    Fp S1 = fp_mul(a.y, fp_mul(b.z, Z2Z2));
    Fp S2 = fp_mul(b.y, fp_mul(a.z, Z1Z1));
    if (fp_eq(U1, U2)) {
        if (fp_eq(S1, S2)) return g1_dbl(a);
        return g1_identity();
    }
    Fp H = fp_sub(U2, U1);
    Fp I = fp_sqr(fp_dbl(H));
    Fp J = fp_mul(H, I);
    Fp K = fp_dbl(fp_sub(S2, S1));
    Fp V = fp_mul(U1, I);
    G1 r;
    r.x = fp_sub(fp_sub(fp_sqr(K), J), fp_dbl(V));
    Fp t = fp_mul(K, fp_sub(V, r.x));
    r.y = fp_sub(t, fp_dbl(fp_mul(S1, J)));
    Fp z = fp_add(a.z, b.z);
    z = fp_sqr(z);
    z = fp_sub(z, Z1Z1);
    z = fp_sub(z, Z2Z2);
    r.z = fp_mul(z, H);
    return r;
}

// madd-2007-bl: Jacobian + affine.
static inline G1 g1_madd(thread const G1 &a, thread const G1A &b) {
    if (g1a_is_identity(b)) return a;
    if (fp_is_zero(a.z)) {
        G1 r;
        r.x = b.x;
        r.y = b.y;
        r.z = fp_one();
        return r;
    }
    Fp Z1Z1 = fp_sqr(a.z);
    Fp U2 = fp_mul(b.x, Z1Z1);
    Fp S2 = fp_mul(b.y, fp_mul(a.z, Z1Z1));
    if (fp_eq(a.x, U2)) {
        if (fp_eq(a.y, S2)) return g1_dbl(a);
        return g1_identity();
    }
    Fp H = fp_sub(U2, a.x);
    Fp HH = fp_sqr(H);
    Fp I = fp_dbl(fp_dbl(HH));
    Fp J = fp_mul(H, I);
    Fp K = fp_dbl(fp_sub(S2, a.y));
    Fp V = fp_mul(a.x, I);
    G1 r;
    r.x = fp_sub(fp_sub(fp_sqr(K), J), fp_dbl(V));
    Fp t = fp_mul(K, fp_sub(V, r.x));
    r.y = fp_sub(t, fp_dbl(fp_mul(a.y, J)));
    Fp z = fp_add(a.z, H);
    z = fp_sqr(z);
    z = fp_sub(z, Z1Z1);
    r.z = fp_sub(z, HH);
    return r;
}

// ------------------------------------------------------------ memory access

static inline Fp fp_load(device const uint *p) {
    Fp r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.v[i] = p[i];
    return r;
}

static inline void fp_store(device uint *p, thread const Fp &a) {
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) p[i] = a.v[i];
}

static inline G1A g1a_load(device const uint *p) {
    G1A r;
    r.x = fp_load(p);
    r.y = fp_load(p + FP_NLIMBS);
    return r;
}

static inline void g1a_store(device uint *p, thread const G1A &a) {
    fp_store(p, a.x);
    fp_store(p + FP_NLIMBS, a.y);
}

static inline G1 g1_load(device const uint *p) {
    G1 r;
    r.x = fp_load(p);
    r.y = fp_load(p + FP_NLIMBS);
    r.z = fp_load(p + 2 * FP_NLIMBS);
    return r;
}

static inline void g1_store(device uint *p, thread const G1 &a) {
    fp_store(p, a.x);
    fp_store(p + FP_NLIMBS, a.y);
    fp_store(p + 2 * FP_NLIMBS, a.z);
}

static inline G1 g1_load_tg(threadgroup const uint *p) {
    G1 r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.x.v[i] = p[i];
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.y.v[i] = p[FP_NLIMBS + i];
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.z.v[i] = p[2 * FP_NLIMBS + i];
    return r;
}

static inline void g1_store_tg(threadgroup uint *p, thread const G1 &a) {
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) p[i] = a.x.v[i];
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) p[FP_NLIMBS + i] = a.y.v[i];
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) p[2 * FP_NLIMBS + i] = a.z.v[i];
}

static inline Fr fr_load(device const uint *p) {
    Fr r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) r.v[i] = p[i];
    return r;
}

static inline void fr_store(device uint *p, thread const Fr &a) {
#pragma clang loop unroll(full)
    for (int i = 0; i < FR_NLIMBS; i++) p[i] = a.v[i];
}

// ---------------------------------------------------- SIMD-group reduction

static inline G1 g1_shuffle_down(thread const G1 &p, ushort delta) {
    G1 r;
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.x.v[i] = simd_shuffle_down(p.x.v[i], delta);
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.y.v[i] = simd_shuffle_down(p.y.v[i], delta);
#pragma clang loop unroll(full)
    for (int i = 0; i < FP_NLIMBS; i++) r.z.v[i] = simd_shuffle_down(p.z.v[i], delta);
    return r;
}

// Collapses 128 buckets into sum_{k=1}^{128} k * B[k-1].
//
// L_REDUCE_LANES lanes cooperate on one output, each first collapsing a
// contiguous run of buckets with a serial running sum, then combining across
// lanes with a shuffle tree.  The split matters: a pure shuffle tree over all
// 128 buckets executes at full SIMD width on every level, so 32 lanes do the
// work of one useful merge -- measured 40ms per phase.  Doing the bulk serially
// inside a lane and only the last log2(L_REDUCE_LANES) levels as a tree keeps
// the wasted width down while keeping the dependency chain short.
//
// Merging two adjacent ranges of h lanes each:
//     rs = rs_lo + rs_hi
//     w  = w_lo + w_hi + h * s_hi
//     s  = s_lo + s_hi
// and h is a power of two, so the scaling is doublings.
static inline G1 reduce_buckets(device const uint *buckets, uint pos) {
    const uint per_lane = L_NUM_BUCKETS / L_REDUCE_LANES;

    // Serial running sum over this lane's slice, from the top down, giving
    // rs = sum_i (i+1) * B[base+i] and s = sum_i B[base+i].
    G1 s = g1_identity();
    G1 rs = g1_identity();
    for (uint i = per_lane; i-- > 0u;) {
        const G1 bk = g1_load(buckets + (ulong)(pos * per_lane + i) * L_JACOBIAN_WORDS);
        s = g1_add(s, bk);
        rs = g1_add(rs, s);
    }
    G1 w = g1_identity();

    for (uint level = 0u; (1u << level) < L_REDUCE_LANES; level++) {
        const ushort h = (ushort)(1u << level);
        // Every lane must reach the shuffle, so compute first and commit after.
        const G1 sb = g1_shuffle_down(s, h);
        const G1 wb = g1_shuffle_down(w, h);
        const G1 rb = g1_shuffle_down(rs, h);
        G1 hs = sb;
        for (uint t = 0u; t < level; t++) hs = g1_dbl(hs);
        const G1 nw = g1_add(w, g1_add(wb, hs));
        const G1 ns = g1_add(s, sb);
        const G1 nr = g1_add(rs, rb);
        if ((pos & ((1u << (level + 1u)) - 1u)) == 0u) {
            w = nw;
            s = ns;
            rs = nr;
        }
    }

    // Lane 0 holds rs = sum_p RS_p and w = sum_p p * GS_p, and
    //     sum_k (k+1) B_k = sum_p [ RS_p + per_lane * p * GS_p ].
    for (uint t = 0u; t < L_LOG_REDUCE_PER_LANE; t++) w = g1_dbl(w);
    return g1_add(rs, w);
}

#line 1 "src/shaders/kernels.metal"
// Compute kernels for the EIP-7594 cell proof pipeline.
//
// Dispatch order for a batch of B blobs:
//
//   k_blob_to_fr        blob bytes -> bit-reversed Lagrange values
//   k_ntt_pass x2       inverse transform of size 4096 -> monomial coefficients
//   k_ntt_pass x2       forward transform of size 8192 -> extended evaluations
//   k_serialize_cells   evaluations -> cell bytes
//   k_build_circulant   64 circulant columns, each transformed to size 128
//   k_phase_a_accum     fixed-base bucket MSM against the precomputed setup
//   k_bucket_reduce     buckets -> u[j]
//   k_ladder            u[j] -> 2^(8d) * u[j]
//   (host normalises the ladder to affine)
//   k_phase_b_accum     circulant bucket MSM over the ladder
//   k_bucket_reduce     buckets -> proofs
//
// Every kernel takes the blob index in `.y` of the grid, so batching is just a
// wider dispatch.

static inline uint brev(uint x, uint bits) { return reverse_bits(x) >> (32u - bits); }

// ------------------------------------------------------------ deserialisation

kernel void k_blob_to_fr(device uint *out [[buffer(0)]], device const uchar *blob [[buffer(1)]],
                         device atomic_uint *err [[buffer(2)]],
                         uint2 gid [[thread_position_in_grid]]) {
    const uint i = gid.x;
    const uint b = gid.y;
    device const uchar *src = blob + (ulong)b * L_BYTES_PER_BLOB + (ulong)i * 32u;

    // 32 big-endian bytes -> 8 little-endian 32-bit limbs.
    Fr v;
#pragma clang loop unroll(full)
    for (int limb = 0; limb < FR_NLIMBS; limb++) {
        const uint off = (uint)(7 - limb) * 4u;
        v.v[limb] = ((uint)src[off] << 24) | ((uint)src[off + 1] << 16) |
                    ((uint)src[off + 2] << 8) | (uint)src[off + 3];
    }
    if (!fr_is_canonical(v)) {
        atomic_fetch_or_explicit(err, 1u, memory_order_relaxed);
    }
    const Fr m = fr_from_canonical(v);
    // The blob holds evaluations in bit-reversed order; undo that here so the
    // inverse transform sees natural order.
    const uint dst = brev(i, L_LOG_BLOB);
    fr_store(out + ((ulong)b * L_FIELD_ELEMENTS_PER_BLOB + dst) * FR_NLIMBS, m);
}

kernel void k_serialize_cells(device uchar *out [[buffer(0)]], device const uint *evals [[buffer(1)]],
                              uint2 gid [[thread_position_in_grid]]) {
    const uint i = gid.x;
    const uint b = gid.y;
    Fr v = fr_load(evals + ((ulong)b * L_FIELD_ELEMENTS_PER_EXT_BLOB + i) * FR_NLIMBS);
    v = fr_to_canonical(v);
    const uint dst = brev(i, L_LOG_EXT_BLOB);
    device uchar *o = out + (ulong)b * (L_FIELD_ELEMENTS_PER_EXT_BLOB * 32u) + (ulong)dst * 32u;
#pragma clang loop unroll(full)
    for (int limb = 0; limb < FR_NLIMBS; limb++) {
        const uint w = v.v[limb];
        const uint off = (uint)(7 - limb) * 4u;
        o[off + 0] = (uchar)(w >> 24);
        o[off + 1] = (uchar)(w >> 16);
        o[off + 2] = (uchar)(w >> 8);
        o[off + 3] = (uchar)w;
    }
}

// ------------------------------------------------------------------ transforms

// One pass of a four-step (N = N1 * N2) transform.  Each threadgroup owns one
// sub-transform, held in threadgroup memory, so a 4096 or 8192 point transform
// costs two dispatches instead of one per radix-2 stage.
struct NttParams {
    uint n;              // sub-transform size (<= 128)
    uint log_n;
    uint in_stride_t;    // element stride between transforms, input
    uint in_stride_i;    // element stride within a transform, input
    uint out_stride_t;
    uint out_stride_i;
    uint root_stride;    // 8192 / n, to index the shared root table
    uint twiddle_stride; // 8192 / N for the inter-pass twiddle, or 0 for none
    uint full_n;         // N
    uint in_batch;       // elements per blob, input
    uint out_batch;      // elements per blob, output
    uint scale;          // non-zero to multiply the result by scale_val
    uint scale_val[FR_NLIMBS];
};

kernel void k_ntt_pass(device uint *out [[buffer(0)]], device const uint *in [[buffer(1)]],
                       device const uint *roots [[buffer(2)]], constant NttParams &P [[buffer(3)]],
                       uint2 tgid [[threadgroup_position_in_grid]],
                       uint2 tid2 [[thread_position_in_threadgroup]]) {
    const uint tid = tid2.x;
    threadgroup uint tile[L_CIRCULANT_SIZE * FR_NLIMBS];

    const uint t = tgid.x;
    const uint b = tgid.y;
    device const uint *src = in + (ulong)b * P.in_batch * FR_NLIMBS;
    device uint *dst = out + (ulong)b * P.out_batch * FR_NLIMBS;

    if (tid < P.n) {
        const Fr v = fr_load(src + (ulong)(t * P.in_stride_t + tid * P.in_stride_i) * FR_NLIMBS);
        const uint j = brev(tid, P.log_n);
#pragma clang loop unroll(full)
        for (int k = 0; k < FR_NLIMBS; k++) tile[j * FR_NLIMBS + k] = v.v[k];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    for (uint len = 2u; len <= P.n; len <<= 1) {
        const uint hlen = len >> 1;
        const uint step = P.n / len;
        if (tid < (P.n >> 1)) {
            const uint blk = tid / hlen;
            const uint j = tid - blk * hlen;
            const uint base = blk * len;
            const Fr w = fr_load(roots + (ulong)(j * step * P.root_stride) * FR_NLIMBS);
            Fr a, c;
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) a.v[k] = tile[(base + j) * FR_NLIMBS + k];
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) c.v[k] = tile[(base + j + hlen) * FR_NLIMBS + k];
            c = fr_mul(c, w);
            const Fr s = fr_add(a, c);
            const Fr d = fr_sub(a, c);
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) tile[(base + j) * FR_NLIMBS + k] = s.v[k];
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) tile[(base + j + hlen) * FR_NLIMBS + k] = d.v[k];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }

    if (tid < P.n) {
        Fr v;
#pragma clang loop unroll(full)
        for (int k = 0; k < FR_NLIMBS; k++) v.v[k] = tile[tid * FR_NLIMBS + k];
        if (P.twiddle_stride != 0u) {
            const uint e = (t * tid) % P.full_n;
            v = fr_mul(v, fr_load(roots + (ulong)(e * P.twiddle_stride) * FR_NLIMBS));
        }
        if (P.scale != 0u) {
            Fr s;
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) s.v[k] = P.scale_val[k];
            v = fr_mul(v, s);
        }
        fr_store(dst + (ulong)(t * P.out_stride_t + tid * P.out_stride_i) * FR_NLIMBS, v);
    }
}

// Builds the 64 circulant first-columns from the polynomial, transforms each to
// size 128, and writes the result transposed so that phase A reads one
// contiguous scalar vector per output.
kernel void k_build_circulant(device uint *coeffs [[buffer(0)]], device const uint *poly [[buffer(1)]],
                              device const uint *roots [[buffer(2)]],
                              uint2 tgid [[threadgroup_position_in_grid]],
                              uint2 tid2 [[thread_position_in_threadgroup]]) {
    const uint tid = tid2.x;
    threadgroup uint tile[L_CIRCULANT_SIZE * FR_NLIMBS];

    const uint i = tgid.x; // circulant offset, 0..63
    const uint b = tgid.y;
    // The polynomial lives in the zero-padded 8192-element buffer that feeds the
    // forward transform, so the per-blob stride is the extended one.
    device const uint *p = poly + (ulong)b * L_FIELD_ELEMENTS_PER_EXT_BLOB * FR_NLIMBS;

    // c_i[0] = poly[d - i]; c_i[128 - j] = poly[d - i - 64j] for j in 1..62.
    const uint d = L_FIELD_ELEMENTS_PER_BLOB - 1u;
    Fr v = fr_zero();
    if (tid == 0u) {
        v = fr_load(p + (ulong)(d - i) * FR_NLIMBS);
    } else if (tid >= 66u) {
        const uint j = L_CIRCULANT_SIZE - tid; // 1..62
        v = fr_load(p + (ulong)(d - i - j * L_FIELD_ELEMENTS_PER_CELL) * FR_NLIMBS);
    }
    {
        const uint br = brev(tid, L_LOG_CIRCULANT);
#pragma clang loop unroll(full)
        for (int k = 0; k < FR_NLIMBS; k++) tile[br * FR_NLIMBS + k] = v.v[k];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    const uint root_stride = L_FIELD_ELEMENTS_PER_EXT_BLOB / L_CIRCULANT_SIZE;
    for (uint len = 2u; len <= L_CIRCULANT_SIZE; len <<= 1) {
        const uint hlen = len >> 1;
        const uint step = L_CIRCULANT_SIZE / len;
        if (tid < (L_CIRCULANT_SIZE / 2u)) {
            const uint blk = tid / hlen;
            const uint jj = tid - blk * hlen;
            const uint base = blk * len;
            const Fr w = fr_load(roots + (ulong)(jj * step * root_stride) * FR_NLIMBS);
            Fr a, c;
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) a.v[k] = tile[(base + jj) * FR_NLIMBS + k];
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) c.v[k] = tile[(base + jj + hlen) * FR_NLIMBS + k];
            c = fr_mul(c, w);
            const Fr s = fr_add(a, c);
            const Fr q = fr_sub(a, c);
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) tile[(base + jj) * FR_NLIMBS + k] = s.v[k];
#pragma clang loop unroll(full)
            for (int k = 0; k < FR_NLIMBS; k++) tile[(base + jj + hlen) * FR_NLIMBS + k] = q.v[k];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }

    {
        Fr r;
#pragma clang loop unroll(full)
        for (int k = 0; k < FR_NLIMBS; k++) r.v[k] = tile[tid * FR_NLIMBS + k];
        // coeffs[j][i], j == tid
        fr_store(coeffs + ((ulong)b * L_CIRCULANT_SIZE * L_PHASE_A_TERMS +
                           (ulong)tid * L_PHASE_A_TERMS + i) *
                              FR_NLIMBS,
                 r);
    }
}

// ------------------------------------------------------------------- phase A

// One threadgroup per output j, one thread per bucket, reduction fused in.
//
// The digits are bucket-sorted in threadgroup memory first.  Without that, a
// SIMD group would step through all 2048 items with at most a couple of lanes
// doing a point addition at a time; sorting keeps every lane busy and costs a
// few microseconds of integer work against milliseconds of curve arithmetic.
// The recoding runs twice -- once to histogram, once to scatter -- because
// keeping the digits around costs 4KB of threadgroup memory, and threadgroup
// memory is what caps residency here.
kernel void k_phase_a(device uint *out [[buffer(0)]], device const uint *coeffs [[buffer(1)]],
                      device const uint *table [[buffer(2)]],
                      uint2 tgid [[threadgroup_position_in_grid]],
                      uint2 tid2 [[thread_position_in_threadgroup]]) {
    const uint tid = tid2.x;
    threadgroup ushort tg_sorted[L_PHASE_A_ITEMS];
    threadgroup atomic_uint tg_count[L_NUM_BUCKETS];
    threadgroup uint tg_start[L_NUM_BUCKETS + 1];

    const uint j = tgid.x;
    const uint b = tgid.y;

    atomic_store_explicit(&tg_count[tid], 0u, memory_order_relaxed);
    threadgroup_barrier(mem_flags::mem_threadgroup);

    // Signed-digit recoding of this thread's scalar.  digit = byte + carry, and
    // if it exceeds the half window we borrow from the next digit; scalars are
    // below r < 2^255 so the carry chain always terminates inside 32 digits.
    Fr scalar;
    if (tid < L_PHASE_A_TERMS) {
        scalar = fr_load(coeffs + ((ulong)b * L_CIRCULANT_SIZE * L_PHASE_A_TERMS +
                                   (ulong)j * L_PHASE_A_TERMS + tid) *
                                      FR_NLIMBS);
        scalar = fr_to_canonical(scalar);
        int carry = 0;
#pragma clang loop unroll(full)
        for (uint dd = 0u; dd < L_NUM_DIGITS; dd++) {
            const uint byte = (scalar.v[dd >> 2] >> ((dd & 3u) * 8u)) & 0xffu;
            int v = (int)byte + carry;
            carry = 0;
            if (v > L_NUM_BUCKETS) {
                v -= 2 * L_NUM_BUCKETS;
                carry = 1;
            }
            if (v != 0) {
                const uint bucket = (uint)(v < 0 ? -v : v) - 1u;
                atomic_fetch_add_explicit(&tg_count[bucket], 1u, memory_order_relaxed);
            }
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    if (tid == 0u) {
        uint acc = 0u;
        for (uint k = 0u; k < L_NUM_BUCKETS; k++) {
            tg_start[k] = acc;
            acc += atomic_load_explicit(&tg_count[k], memory_order_relaxed);
            atomic_store_explicit(&tg_count[k], tg_start[k], memory_order_relaxed);
        }
        tg_start[L_NUM_BUCKETS] = acc;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    // Scatter into bucket order; tg_count is now a per-bucket write cursor.
    if (tid < L_PHASE_A_TERMS) {
        int carry = 0;
#pragma clang loop unroll(full)
        for (uint dd = 0u; dd < L_NUM_DIGITS; dd++) {
            const uint byte = (scalar.v[dd >> 2] >> ((dd & 3u) * 8u)) & 0xffu;
            int v = (int)byte + carry;
            carry = 0;
            if (v > L_NUM_BUCKETS) {
                v -= 2 * L_NUM_BUCKETS;
                carry = 1;
            }
            if (v != 0) {
                const uint neg = v < 0 ? 1u : 0u;
                const uint bucket = (uint)(v < 0 ? -v : v) - 1u;
                const uint slot =
                    atomic_fetch_add_explicit(&tg_count[bucket], 1u, memory_order_relaxed);
                tg_sorted[slot] = (ushort)((tid << 6) | (dd << 1) | neg);
            }
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    G1 acc = g1_identity();
    {
        const uint lo = tg_start[tid];
        const uint hi = tg_start[tid + 1u];
        device const uint *tbase =
            table + (ulong)j * L_PHASE_A_TERMS * L_NUM_DIGITS * L_AFFINE_WORDS;
        for (uint it = lo; it < hi; it++) {
            const uint packed = tg_sorted[it];
            const uint i = packed >> 6;
            const uint dd = (packed >> 1) & 31u;
            G1A pt = g1a_load(tbase + (ulong)(i * L_NUM_DIGITS + dd) * L_AFFINE_WORDS);
            if ((packed & 1u) != 0u) pt.y = fp_neg(pt.y);
            acc = g1_madd(acc, pt);
        }
    }

    g1_store(out + ((ulong)b * L_CIRCULANT_SIZE * L_NUM_BUCKETS + (ulong)j * L_NUM_BUCKETS + tid) *
                       L_JACOBIAN_WORDS,
             acc);
}

// ------------------------------------------------------------------- phase B

// out[a] = sum_e kappa[e] * u[a - e], the fused IFFT/truncate/FFT map.
//
// The taps and their signed digits are identical for every output -- only the
// point index rotates -- so the bucket-sorted item list comes precomputed from
// the host and no sorting happens here.
kernel void k_phase_b(device uint *out [[buffer(0)]], device const uint *ladder [[buffer(1)]],
                      device const uint *items [[buffer(2)]],
                      device const uint *offsets [[buffer(3)]],
                      uint2 tgid [[threadgroup_position_in_grid]],
                      uint2 tid2 [[thread_position_in_threadgroup]]) {
    const uint tid = tid2.x;
    const uint a = tgid.x;
    const uint b = tgid.y;
    const uint lo = offsets[tid];
    const uint hi = offsets[tid + 1u];
    device const uint *lbase =
        ladder + (ulong)b * L_CIRCULANT_SIZE * L_LADDER_POSITIONS * L_AFFINE_WORDS;

    G1 acc = g1_identity();
    for (uint it = lo; it < hi; it++) {
        const uint packed = items[it];
        const uint e = packed & 0xffu;
        const uint d = (packed >> 8) & 0xffu;
        const uint sign = (packed >> 16) & 1u;
        const uint src = (a - e) & (L_CIRCULANT_SIZE - 1u);
        G1A pt = g1a_load(lbase + (ulong)(src * L_LADDER_POSITIONS + d) * L_AFFINE_WORDS);
        if (sign != 0u) pt.y = fp_neg(pt.y);
        acc = g1_madd(acc, pt);
    }

    g1_store(out + ((ulong)b * L_CIRCULANT_SIZE * L_NUM_BUCKETS + (ulong)a * L_NUM_BUCKETS + tid) *
                       L_JACOBIAN_WORDS,
             acc);
}

// ---------------------------------------------------------- bucket reduction

// One SIMD group serves L_REDUCE_LANES-sized teams; a 128-thread threadgroup
// therefore reduces 16 outputs at once with no threadgroup memory at all.
kernel void k_bucket_reduce(device uint *out [[buffer(0)]], device const uint *buckets [[buffer(1)]],
                            uint2 tgid [[threadgroup_position_in_grid]],
                            uint2 tid2 [[thread_position_in_threadgroup]]) {
    const uint tid = tid2.x;
    const uint team = tid / L_REDUCE_LANES;
    const uint pos = tid % L_REDUCE_LANES;
    const uint j = tgid.x * L_REDUCE_OUTPUTS_PER_TG + team;
    const uint b = tgid.y;

    device const uint *base =
        buckets + ((ulong)b * L_CIRCULANT_SIZE * L_NUM_BUCKETS + (ulong)j * L_NUM_BUCKETS) *
                      L_JACOBIAN_WORDS;
    const G1 total = reduce_buckets(base, pos);
    if (pos == 0u) {
        g1_store(out + ((ulong)b * L_CIRCULANT_SIZE + j) * L_JACOBIAN_WORDS, total);
    }
}

)KZGPU_SHADER_SRC";
} // namespace kzgpu
