/* Generated by tools/gen_constants.py -- do not edit. */
#pragma once

/* Base field p (381 bits), 6 x 64-bit limbs, little endian. */
#define VKZG_FP_P { 0xb9feffffffffaaabULL, 0x1eabfffeb153ffffULL, 0x6730d2a0f6b0f624ULL, 0x64774b84f38512bfULL, 0x4b1ba7b6434bacd7ULL, 0x1a0111ea397fe69aULL }
#define VKZG_FP_N0 0x89f3fffcfffcfffdULL
#define VKZG_FP_R { 0x760900000002fffdULL, 0xebf4000bc40c0002ULL, 0x5f48985753c758baULL, 0x77ce585370525745ULL, 0x5c071a97a256ec6dULL, 0x15f65ec3fa80e493ULL }
#define VKZG_FP_R2 { 0xf4df1f341c341746ULL, 0x0a76e6a609d104f1ULL, 0x8de5476c4c95b6d5ULL, 0x67eb88a9939d83c0ULL, 0x9a793e85b519952dULL, 0x11988fe592cae3aaULL }
#define VKZG_FP_P_MINUS_3_DIV_4 { 0xee7fbfffffffeaaaULL, 0x07aaffffac54ffffULL, 0xd9cc34a83dac3d89ULL, 0xd91dd2e13ce144afULL, 0x92c6e9ed90d2eb35ULL, 0x0680447a8e5ff9a6ULL }
#define VKZG_FP_P_MINUS_2 { 0xb9feffffffffaaa9ULL, 0x1eabfffeb153ffffULL, 0x6730d2a0f6b0f624ULL, 0x64774b84f38512bfULL, 0x4b1ba7b6434bacd7ULL, 0x1a0111ea397fe69aULL }
#define VKZG_FP_BETA { 0xcd03c9e48671f071ULL, 0x5dab22461fcda5d2ULL, 0x587042afd3851b95ULL, 0x8eb60ebe01bacb9eULL, 0x03f97d6e83d050d2ULL, 0x18f0206554638741ULL }

/* Scalar field r (255 bits), 4 x 64-bit limbs. */
#define VKZG_FR_R_MOD { 0xffffffff00000001ULL, 0x53bda402fffe5bfeULL, 0x3339d80809a1d805ULL, 0x73eda753299d7d48ULL }
#define VKZG_FR_N0 0xfffffffeffffffffULL
#define VKZG_FR_ONE { 0x00000001fffffffeULL, 0x5884b7fa00034802ULL, 0x998c4fefecbc4ff5ULL, 0x1824b159acc5056fULL }
#define VKZG_FR_R2 { 0xc999e990f3f29c6dULL, 0x2b6cedcb87925c23ULL, 0x05d314967254398fULL, 0x0748d9d99f59ff11ULL }
#define VKZG_FR_R_MINUS_2 { 0xfffffffeffffffffULL, 0x53bda402fffe5bfeULL, 0x3339d80809a1d805ULL, 0x73eda753299d7d48ULL }
#define VKZG_FR_ROOT_8192 { 0xa33d279ff0ccffc9ULL, 0x41fac79f59e91972ULL, 0x065d227fead1139bULL, 0x71db41abda03e055ULL }

/* GLV endomorphism, used by the subgroup check. */
#define VKZG_GLV_LAMBDA_INT { 0x00000000ffffffffULL, 0xac45a4010001a402ULL, 0x0000000000000000ULL, 0x0000000000000000ULL }
