#!/usr/bin/env python3
"""Concatenate the Metal sources into a single C++ string literal.

The Metal offline compiler ships with Xcode, not with the Command Line Tools,
so the library compiles its shaders from source at load time (and caches the
resulting binary).  Embedding the source keeps the built library
self-contained -- no .metallib to locate at runtime.

Usage: embed_shaders.py <out.h> <in1> <in2> ...
"""
import sys

DELIM = "KZGPU_SHADER_SRC"


def main():
    out_path, inputs = sys.argv[1], sys.argv[2:]
    parts = ["#include <metal_stdlib>\nusing namespace metal;\n"]
    for path in inputs:
        with open(path) as f:
            text = f.read()
        if DELIM in text:
            raise SystemExit(f"{path} contains the raw-string delimiter {DELIM}")
        parts.append(f"\n#line 1 \"{path}\"\n")
        parts.append(text)
    source = "".join(parts)

    with open(out_path, "w") as f:
        f.write("// Generated by tools/embed_shaders.py -- do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("namespace kzgpu {\n")
        f.write(f"inline const char *kShaderSource = R\"{DELIM}(\n")
        f.write(source)
        f.write(f"\n){DELIM}\";\n")
        f.write("} // namespace kzgpu\n")
    print(f"embedded {len(source)} bytes of MSL into {out_path}")


if __name__ == "__main__":
    main()
