#!/usr/bin/env python3
"""Compile the GLSL compute kernels to SPIR-V and embed them as byte arrays.

Vulkan consumes SPIR-V modules, not shader source, so (unlike the Metal
original, which embedded MSL source and compiled it at load time) this embeds
the SPIR-V words compiled ahead of time by glslangValidator. Either way the
built library stays self-contained: no .spv files to locate at runtime.

Usage: embed_shaders.py <out.h> <glslangValidator> <include_dirs> <k1.comp> <k2.comp> ...

<include_dirs> is a colon-separated list of directories searched for
`#include`, in addition to each shader's own directory.
"""
import os
import subprocess
import sys
import tempfile


def compile_to_spv(glslang, include_dirs, src_path):
    with tempfile.TemporaryDirectory() as td:
        out_path = os.path.join(td, "out.spv")
        cmd = [glslang, "-V", "--target-env", "vulkan1.2"]
        for d in include_dirs.split(":"):
            if d:
                cmd.append("-I" + d)
        cmd += ["-I" + os.path.dirname(src_path), "-o", out_path, src_path]
        subprocess.run(cmd, check=True)
        with open(out_path, "rb") as f:
            data = f.read()
    if len(data) % 4 != 0:
        raise SystemExit(f"{src_path}: SPIR-V output is not word-aligned")
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    return words


def main():
    out_path, glslang, include_dirs = sys.argv[1], sys.argv[2], sys.argv[3]
    inputs = sys.argv[4:]

    kernels = []
    for path in inputs:
        name = os.path.splitext(os.path.basename(path))[0]
        words = compile_to_spv(glslang, include_dirs, path)
        kernels.append((name, words))

    with open(out_path, "w") as f:
        f.write("// Generated by tools/embed_shaders.py -- do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n#include <cstdint>\n\n")
        f.write("namespace vkp {\n\n")
        f.write("struct ShaderSpv {\n")
        f.write("    const char *name;\n")
        f.write("    const uint32_t *code;\n")
        f.write("    size_t words;\n")
        f.write("};\n\n")
        for name, words in kernels:
            f.write(f"inline const uint32_t k_spv_{name}[] = {{\n")
            for i in range(0, len(words), 8):
                chunk = words[i:i + 8]
                f.write("    " + "".join(f"0x{w:08x}u," for w in chunk) + "\n")
            f.write("};\n\n")
        f.write("inline const ShaderSpv kShaders[] = {\n")
        for name, words in kernels:
            f.write(f'    {{"{name}", k_spv_{name}, {len(words)}}},\n')
        f.write("};\n\n")
        f.write("inline constexpr size_t kShaderCount = sizeof(kShaders) / sizeof(kShaders[0]);\n\n")
        f.write("} // namespace vkp\n")

    total = sum(len(w) for _, w in kernels)
    print(f"embedded {len(kernels)} kernels, {total * 4} bytes of SPIR-V -> {out_path}")


if __name__ == "__main__":
    main()
