#!/usr/bin/env python3
"""Embed the monomial G1 trusted setup into the library as a byte array.

Provenance tool, not part of the build: the values are fixed for mainnet and
the generated files are committed.  Run it against a trusted_setup.txt to
confirm the committed blob matches the ceremony output, or to retarget the
library at a different ceremony.

Only the monomial G1 section is needed -- the Lagrange G1 points are for
commitments and the G2 points are for verification, neither of which this
library does. That is 4096 compressed points, 48 bytes each: 192 KiB.

The values are fixed for mainnet and will never change, so baking them in
removes the runtime file dependency entirely.

Usage: python3 tools/embed_setup.py <trusted_setup.txt> <out.h>
"""
import hashlib
import sys

BYTES_PER_G1 = 48


def parse(path):
    """Returns the monomial G1 section of a trusted_setup.txt.

    Layout is: n1, n2, then n1 Lagrange G1 points, n2 G2 points, and finally
    n1 monomial G1 points.
    """
    with open(path) as f:
        tokens = f.read().split()
    n1 = int(tokens[0])
    n2 = int(tokens[1])
    body = tokens[2:]
    expected = n1 + n2 + n1
    if len(body) != expected:
        raise SystemExit(f"expected {expected} hex lines, found {len(body)}")
    monomial = body[n1 + n2:]
    if len(monomial) != n1:
        raise SystemExit("monomial section has the wrong length")
    out = bytearray()
    for line in monomial:
        point = bytes.fromhex(line)
        if len(point) != BYTES_PER_G1:
            raise SystemExit(f"point is {len(point)} bytes, expected {BYTES_PER_G1}")
        out += point
    return n1, bytes(out)


def main():
    setup_path, out_path = sys.argv[1], sys.argv[2]
    count, data = parse(setup_path)
    digest = hashlib.sha256(data).hexdigest()

    lines = [
        "/* Generated by tools/embed_setup.py -- do not edit. */\n",
        "#pragma once\n\n",
        "#include <cstddef>\n#include <cstdint>\n\n",
        "namespace vkzg {\n\n",
        "/*\n",
        f" * Monomial-form G1 trusted setup: {count} compressed points, "
        f"{BYTES_PER_G1} bytes each.\n",
        " *\n",
        " * These are the Ethereum mainnet KZG ceremony values and are fixed for the\n",
        " * lifetime of the protocol, so they are compiled in rather than loaded.\n",
        f" * sha256 of the bytes below: {digest}\n",
        " *\n",
        " * To re-verify against the canonical ceremony output:\n",
        " *   python3 tools/embed_setup.py <trusted_setup.txt> /tmp/check.h\n",
        " * and compare the sha256 it prints with the one above.\n",
        " */\n",
        f"constexpr size_t kEmbeddedSetupSize = {len(data)};\n",
        "extern const uint8_t kEmbeddedSetupG1Monomial[kEmbeddedSetupSize];\n\n",
        "} // namespace vkzg\n",
    ]
    with open(out_path, "w") as f:
        f.writelines(lines)

    # The array itself goes in a .cpp so it is emitted once, not per include.
    src_path = out_path[:-2] + ".cpp" if out_path.endswith(".h") else out_path + ".cpp"
    with open(src_path, "w") as f:
        f.write("/* Generated by tools/embed_setup.py -- do not edit. */\n")
        f.write(f'#include "{out_path.split("/")[-1]}"\n\n')
        f.write("namespace vkzg {\n\n")
        f.write("const uint8_t kEmbeddedSetupG1Monomial[kEmbeddedSetupSize] = {\n")
        for i in range(0, len(data), 24):
            chunk = data[i:i + 24]
            f.write("    " + "".join(f"0x{b:02x}," for b in chunk) + "\n")
        f.write("};\n\n} // namespace vkzg\n")

    print(f"embedded {len(data)} bytes ({count} points) -> {out_path} / {src_path}")
    print(f"  sha256 {digest}")


if __name__ == "__main__":
    main()
