#!/usr/bin/env python3
"""Generate the BLS12-381 field constants the GLSL shaders need.

Usage: python3 tools/gen_constants.py <out_device.h>
"""
import sys

P = 0x1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB
R = 0x73EDA753299D7D483339D80809A1D80553BDA402FFFE5BFEFFFFFFFF00000001  # scalar field modulus


def n0(mod, bits):
    """-mod^{-1} mod 2^bits"""
    inv = 1
    for _ in range(10):
        inv = (inv * (2 - mod * inv)) % (1 << bits)
    return (-inv) % (1 << bits)


def limbs(x, nlimbs, width):
    mask = (1 << width) - 1
    return [(x >> (width * i)) & mask for i in range(nlimbs)]


def fmt(x, nlimbs, width):
    w = width // 4
    return ", ".join(f"0x{v:0{w}x}u" for v in limbs(x, nlimbs, width))


def to_mont(x, mod, bits):
    return (x * (1 << bits)) % mod


def glsl_arr(x, nlimbs, width):
    return f"uint[{nlimbs}]({fmt(x, nlimbs, width)})"


def main():
    dev_path = sys.argv[1]

    d = ["/* Generated by tools/gen_constants.py -- do not edit. */\n"]
    d.append("/* Device-side (GLSL) constants: 32-bit limbs, little endian. */\n")
    d.append("#define FP_NLIMBS 12\n#define FR_NLIMBS 8\n\n")
    d.append(f"const uint FP_P[12] = {glsl_arr(P, 12, 32)};\n")
    d.append(f"const uint FP_N0 = 0x{n0(P, 32):08x}u;\n")
    d.append(f"const uint FP_R[12] = {glsl_arr(to_mont(1, P, 384), 12, 32)};\n")
    # Exponent for the Fermat inversion, and (p-1)/2 for the compressed-point
    # sign bit.  Both are plain integers, not Montgomery values.
    d.append(f"const uint FP_P_MINUS_2[12] = {glsl_arr(P - 2, 12, 32)};\n")
    d.append(f"const uint FP_P_HALF[12] = {glsl_arr((P - 1) // 2, 12, 32)};\n")
    d.append(f"const uint FR_P[8] = {glsl_arr(R, 8, 32)};\n")
    d.append(f"const uint FR_N0 = 0x{n0(R, 32):08x}u;\n")
    d.append(f"const uint FR_R2[8] = {glsl_arr(to_mont(to_mont(1, R, 256), R, 256), 8, 32)};\n")
    open(dev_path, "w").write("".join(d))
    print(f"wrote {dev_path}")


if __name__ == "__main__":
    main()
