/* Generated by tools/embed_setup.py -- do not edit. */
#pragma once

#include <cstddef>
#include <cstdint>

namespace vkp {

/*
 * Monomial-form G1 trusted setup: 4096 compressed points, 48 bytes each.
 *
 * These are the Ethereum mainnet KZG ceremony values and are fixed for the
 * lifetime of the protocol, so they are compiled in rather than loaded.
 * sha256 of the bytes below: 08797579f6cfd5788eddc1a215d64dcfabd04acbcaf2953fb2c1afb830f43315
 *
 * To re-verify against the canonical ceremony output:
 *   python3 tools/embed_setup.py <trusted_setup.txt> /tmp/check.h
 * and compare the sha256 it prints with the one above.
 */
constexpr size_t kEmbeddedSetupSize = 196608;
extern const uint8_t kEmbeddedSetupG1Monomial[kEmbeddedSetupSize];

} // namespace vkp
