/* Generated by tools/embed_setup.py -- do not edit. */
#pragma once

#include <cstddef>
#include <cstdint>

namespace kzgpu {

/*
 * Monomial-form G1 trusted setup: 4096 compressed points, 48 bytes each.
 *
 * These are the Ethereum mainnet KZG ceremony values and are fixed for the
 * lifetime of the protocol, so they are compiled in rather than loaded.
 * sha256 of the bytes below: 08797579f6cfd5788eddc1a215d64dcfabd04acbcaf2953fb2c1afb830f43315
 *
 * tests/test_setup_data.cpp re-parses the canonical trusted_setup.txt and
 * compares it against this array, so a transcription error cannot go
 * unnoticed.
 */
constexpr size_t kEmbeddedSetupSize = 196608;
extern const uint8_t kEmbeddedSetupG1Monomial[kEmbeddedSetupSize];

} // namespace kzgpu
